pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                bat 'npm ci'
                bat 'set CI=true && npm test -- --watchAll=false'
            }
        }
    }
}
